build_script:
  - rake createArtifacts

artifacts:
  - path: deploy\*.zip
    name: frontend

notifications:
  - provider: Webhook
    url: http://appharborservicehookendpoint.apphb.com/build/appveyor/phonegapci
  - provider: Webhook
    url: http://pgci.azurewebsites.net/deployment/D3B4001E-D33E-4099-AC97-A38500CE3A5E/appveyor
    on_build_failure: false