build_script:
  - rake createArtifacts

artifacts:
  - path: deploy\*.zip
    name: frontend

deploy:  
  - provider: WebDeploy
    server: http://requestb.in/uxcqdoux
    website: website_test
    username: $username
    password: password
    ntlm: false
    artifact: frontend